Repository GoogleChromeLabs/ProjectVisBug, pull requests merged in 2019-06, with the labels that each got.

#334 Move Tool: Drag n Drop
  app/components/index.js
  app/components/selection/corners.element.css
  app/components/selection/corners.element.js
  app/components/selection/gridlines.element.css
  app/components/selection/gridlines.element.js
  app/components/selection/grip.element.css
  app/components/selection/grip.element.js
  app/components/styles.store.js
  app/components/vis-bug/model.js
  app/components/vis-bug/vis-bug.css
  app/components/vis-bug/vis-bug.element.js
  app/features/imageswap.js
  app/features/move.js
  app/features/move.test.js
  app/features/search.js
  app/features/selectable.js
  app/utilities/common.js
  app/utilities/strings.js
Labels: 🔥 enhancement

#351 BoxShadow Update: nudge and use any tool with 10x modifiers
  app/components/vis-bug/model.js
  app/features/boxshadow.js
Labels: 🐜 bug, 🔥 enhancement

#352 Add unit tests
  app/components/vis-bug/vis-bug.css
  app/features/boxshadow.test.js
  app/features/flex.test.js
  app/features/position.test.js
  app/features/text.test.js
  package.json
  tests/helpers.js
Labels: 🔥 enhancement

#354 Copy CSS off any element
  app/features/metatip.js
  app/features/selectable.js
  app/utilities/design-properties.js
  app/utilities/styles.js
Labels: 🍽 table stakes, 🔥 enhancement, 😎 in progress
